openapi: "3.0.0"
paths:
  /auth/register:
    post:
      operationId: "AuthController_registerUser"
      parameters: []
      responses:
        201:
          description: ""
  /auth/login:
    post:
      operationId: "AuthController_loginUser"
      parameters: []
      responses:
        201:
          description: ""
  /auth/refresh:
    post:
      operationId: "AuthController_refreshToken"
      parameters: []
      responses:
        201:
          description: ""
info:
  title: "NestJS API"
  description: "The NestJS API description"
  version: "1.0"
  contact: {}
tags:
  - name: "nestjs"
    description: ""
servers: []
components:
  schemas: {}
