openapi: "3.0.0"
paths:
  /auth/register:
    post:
      operationId: "AuthController_registerUser"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCuentaDto"
      responses:
        201:
          description: "Cuenta creada"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateCuentaResponseDto"
  /auth/login:
    post:
      operationId: "AuthController_loginUser"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDto"
      responses:
        200:
          description: "Cuenta creada"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponseDto"
  /auth/refresh:
    post:
      operationId: "AuthController_refreshToken"
      parameters: []
      responses:
        201:
          description: ""
info:
  title: "Expo Backend"
  description: "Backend de las aplicaciones de Expo"
  version: "1.0"
  contact: {}
tags:
  - name: "expo-backend"
    description: ""
servers: []
components:
  schemas:
    CreateCuentaDto:
      type: "object"
      properties:
        username:
          type: "string"
          minLength: 3
          maxLength: 255
        password:
          type: "string"
          minLength: 6
        esAdmin:
          default: false
          type: "boolean"
      required:
        - "username"
        - "password"
    CreateCuentaResponseDto:
      type: "object"
      properties:
        username:
          type: "string"
          minLength: 3
          maxLength: 255
        esAdmin:
          default: false
          type: "boolean"
      required:
        - "username"
    LoginDto:
      type: "object"
      properties:
        username:
          type: "string"
          minLength: 3
          maxLength: 255
        password:
          type: "string"
          minLength: 6
      required:
        - "username"
        - "password"
    LoginResponseDto:
      type: "object"
      properties:
        user:
          type: "object"
          properties:
            id:
              type: "string"
            nombreUsuario:
              type: "string"
            contrasena:
              type: "string"
            esAdmin:
              type: "boolean"
            created_at:
              type: "string"
            updated_at:
              type: "string"
            filtroBaseActivo:
              type: "boolean"
            fcmToken:
              type: "array"
              items:
                type: "string"
          required:
            - "id"
            - "nombreUsuario"
            - "contrasena"
            - "esAdmin"
            - "created_at"
            - "updated_at"
            - "filtroBaseActivo"
            - "fcmToken"
        backendTokens:
          type: "object"
          properties:
            accessToken:
              type: "string"
            refreshToken:
              type: "string"
          required:
            - "accessToken"
            - "refreshToken"
      required:
        - "user"
        - "backendTokens"
