openapi: "3.0.0"
paths:
  /auth/register:
    post:
      operationId: "AuthController_registerUser"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterDto"
      responses:
        201:
          description: "Cuenta creada"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponseDto"
  /auth/login:
    post:
      operationId: "AuthController_loginUser"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDto"
      responses:
        200:
          description: "Cuenta creada"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponseDto"
  /auth/refresh:
    post:
      operationId: "AuthController_refreshToken"
      parameters: []
      responses:
        201:
          description: ""
info:
  title: "Expo Backend"
  description: "Backend de las aplicaciones de Expo"
  version: "1.0"
  contact: {}
tags:
  - name: "expo-backend"
    description: ""
servers: []
components:
  schemas:
    RegisterDto:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
          minLength: 6
        isAdmin:
          default: false
          type: "boolean"
      required:
        - "username"
        - "password"
        - "isAdmin"
    RegisterResponseDto:
      type: "object"
      properties:
        username:
          type: "string"
        isAdmin:
          default: false
          type: "boolean"
      required:
        - "username"
        - "isAdmin"
    LoginDto:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
          minLength: 6
      required:
        - "username"
        - "password"
    LoginResponseDto:
      type: "object"
      properties:
        user:
          type: "object"
          properties:
            id:
              type: "string"
              format: "uuid"
            username:
              type: "string"
            isAdmin:
              default: false
              type: "boolean"
            created_at:
              type: "string"
              format: "date-time"
            updated_at:
              type: "string"
              format: "date-time"
            filtroBase:
              type: "object"
              properties:
                etiquetas:
                  type: "object"
                  properties:
                    id:
                      type: "string"
                      format: "uuid"
                    name:
                      type: "string"
                      minLength: 1
                    grupo:
                      type: "object"
                      properties:
                        id:
                          type: "string"
                          format: "uuid"
                        color:
                          type: "string"
                          minLength: 7
                          maxLength: 7
                        isExclusive:
                          type: "boolean"
                      required:
                        - "id"
                        - "color"
                        - "isExclusive"
                  required:
                    - "id"
                    - "name"
                    - "grupo"
                active:
                  type: "boolean"
              required:
                - "etiquetas"
                - "active"
            filtroBaseActivo:
              default: false
              type: "boolean"
            fcmToken:
              default: []
              type: "array"
              items:
                type: "string"
        backendTokens:
          type: "object"
          properties:
            accessToken:
              type: "string"
            refreshToken:
              type: "string"
      required:
        - "user"
        - "backendTokens"
