openapi: "3.0.0"
paths:
  /:
    get:
      operationId: "AppController_getHello"
      parameters: []
      responses:
        200:
          description: ""
  /test/{id}:
    get:
      operationId: "AppController_test"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: ""
    post:
      operationId: "AppController_testPost"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        201:
          description: ""
    put:
      operationId: "AppController_testPut"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: ""
  /otraRuta/{id1}/{id2}:
    post:
      operationId: "AppController_otraRuta"
      parameters:
        - name: "id1"
          required: true
          in: "path"
          schema:
            type: "string"
        - name: "id2"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        201:
          description: ""
  /auth/register:
    post:
      operationId: "AuthController_registerUser"
      parameters: []
      responses:
        201:
          description: ""
  /auth/login:
    post:
      operationId: "AuthController_loginUser"
      parameters: []
      responses:
        201:
          description: ""
  /auth/refresh:
    post:
      operationId: "AuthController_refreshToken"
      parameters: []
      responses:
        201:
          description: ""
info:
  title: "NestJS API"
  description: "The NestJS API description"
  version: "1.0"
  contact: {}
tags:
  - name: "nestjs"
    description: ""
servers: []
components:
  schemas: {}
