openapi: "3.0.0"
paths:
  /:
    get:
      operationId: "AppController_getHello"
      parameters: []
      responses:
        200:
          description: ""
  /test/{id}:
    get:
      operationId: "AppController_test"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: ""
    post:
      operationId: "AppController_testPost"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        201:
          description: ""
    put:
      operationId: "AppController_testPut"
      parameters:
        - name: "id"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: ""
info:
  title: "Cats example"
  description: "The cats API description"
  version: "1.0"
  contact: {}
tags:
  - name: "cats"
    description: ""
servers: []
components:
  schemas: {}
