/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_loginUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_refreshToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tag/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TagController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tag/all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TagController_findAll'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tag/find-by-group/{groupId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TagController_findByGroup'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tag/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TagController_findById'];
    put?: never;
    post?: never;
    delete: operations['TagController_remove'];
    options?: never;
    head?: never;
    patch: operations['TagController_update'];
    trace?: never;
  };
  '/tag/massive-allocation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TagController_massiveAllocation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tag/massive-deallocation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TagController_massiveDeallocation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/account/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AccountController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/account/global-filter': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AccountController_getGlobalFilter'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['AccountController_updateGlobalFilter'];
    trace?: never;
  };
  '/account/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AccountController_getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tag-group/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TagGroupController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tag-group/all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TagGroupController_findAll'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tag-group/all-with-tags': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TagGroupController_findAllWithTags'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tag-group/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TagGroupController_findById'];
    put?: never;
    post?: never;
    delete: operations['TagGroupController_delete'];
    options?: never;
    head?: never;
    patch: operations['TagGroupController_update'];
    trace?: never;
  };
  '/comment/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CommentController_createComment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/comment/get-by-profile/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CommentController_getCommentsByProfileId'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/comment/toggle-solve/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['CommentController_toggleSolveComment'];
    trace?: never;
  };
  '/location/all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['LocationController_findAll'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/location/provinces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['LocationController_findProvinces'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/location/find-cities-by-province/{province}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['LocationController_findArgCityByProvince'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/location/all-countries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['LocationController_findAllCountries'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/location/states-by-country/{countryCode}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['LocationController_findStatesByCountry'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginDto: {
      username: string;
      password: string;
    };
    LoginResponseDto: {
      user: {
        /** Format: uuid */
        id?: string;
        username?: string;
        /** @enum {string} */
        role?: 'USER' | 'ADMIN';
        /** @default false */
        isGlobalFilterActive: boolean;
        /** @default [] */
        fcmToken: string[];
        /** Format: date-time */
        created_at?: string;
        /** Format: date-time */
        updated_at?: string;
      };
      backendTokens: {
        accessToken?: string;
        refreshToken?: string;
        expiresIn?: number;
      };
    };
    ErrorDto: {
      message: string[];
      statusCode: number;
      error: string;
    };
    RefreshResponseDto: {
      refreshToken: string;
      accessToken: string;
      expiresIn: number;
    };
    CreateTagDto: {
      name: string;
      /** Format: uuid */
      groupId: string;
    };
    CreateTagResponseDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: uuid */
      groupId: string;
      /** @enum {string} */
      type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
    };
    FindAllTagResponseDto: {
      tags: {
        /** Format: uuid */
        id: string;
        name: string;
        /** Format: uuid */
        groupId: string;
        /** @enum {string} */
        type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
        /** Format: date-time */
        created_at: string;
        /** Format: date-time */
        updated_at: string;
        group: {
          /** Format: uuid */
          id: string;
          name: string;
          color: string;
          isExclusive: boolean;
          /** Format: date-time */
          created_at: string;
          /** Format: date-time */
          updated_at: string;
        };
      }[];
    };
    FindByGroupTagResponseDto: {
      tags: {
        /** Format: uuid */
        id: string;
        name: string;
        /** Format: uuid */
        groupId: string;
        /** @enum {string} */
        type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
        /** Format: date-time */
        created_at: string;
        /** Format: date-time */
        updated_at: string;
        group: {
          /** Format: uuid */
          id: string;
          name: string;
          color: string;
          isExclusive: boolean;
          /** Format: date-time */
          created_at: string;
          /** Format: date-time */
          updated_at: string;
        };
      }[];
    };
    FindOneTagResponseDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: uuid */
      groupId: string;
      /** @enum {string} */
      type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      group: {
        /** Format: uuid */
        id?: string;
        name?: string;
        color?: string;
        isExclusive?: boolean;
        /** Format: date-time */
        created_at?: string;
        /** Format: date-time */
        updated_at?: string;
      };
    };
    UpdateTagDto: {
      name: string;
      /** Format: uuid */
      groupId: string;
    };
    UpdateTagResponseDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: uuid */
      groupId: string;
      /** @enum {string} */
      type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    DeleteTagResponseDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: uuid */
      groupId: string;
      /** @enum {string} */
      type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    MassiveAllocationDto: {
      tagIds: string[];
      profileIds: string[];
    };
    MassiveAllocationResponseDto: {
      profiles: {
        /** Format: uuid */
        id: string;
        shortId: number;
        phoneNumber: string;
        secondaryPhoneNumber: string | null;
        fullName: string;
        firstName: string | null;
        gender: string | null;
        /** Format: date-time */
        birthDate: string | null;
        /** Format: uri */
        profilePictureUrl: string | null;
        instagram: string | null;
        /** Format: email */
        mail: string | null;
        dni: string | null;
        alternativeNames: string[] | null;
        /** Format: uuid */
        birthLocationId: string | null;
        /** Format: uuid */
        residenceLocationId: string | null;
        isInTrash: boolean;
        /** Format: date-time */
        movedToTrashDate: string | null;
        /** Format: date-time */
        created_at: string;
        /** Format: date-time */
        updated_at: string;
      }[];
    };
    MassiveDeallocationDto: {
      tagIds: string[];
      profileIds: string[];
    };
    MassiveDeallocationResponseDto: {
      profiles: {
        /** Format: uuid */
        id: string;
        shortId: number;
        phoneNumber: string;
        secondaryPhoneNumber: string | null;
        fullName: string;
        firstName: string | null;
        gender: string | null;
        /** Format: date-time */
        birthDate: string | null;
        /** Format: uri */
        profilePictureUrl: string | null;
        instagram: string | null;
        /** Format: email */
        mail: string | null;
        dni: string | null;
        alternativeNames: string[] | null;
        /** Format: uuid */
        birthLocationId: string | null;
        /** Format: uuid */
        residenceLocationId: string | null;
        isInTrash: boolean;
        /** Format: date-time */
        movedToTrashDate: string | null;
        /** Format: date-time */
        created_at: string;
        /** Format: date-time */
        updated_at: string;
      }[];
    };
    CreateAccountDto: {
      username: string;
      password: string;
      /** @enum {string} */
      role: 'USER' | 'ADMIN';
    };
    CreateAccountResponseDto: {
      /** Format: uuid */
      id: string;
      username: string;
      /** @enum {string} */
      role: 'USER' | 'ADMIN';
      /** @default false */
      isGlobalFilterActive: boolean;
      /** @default [] */
      fcmToken: string[];
    };
    UpdateGlobalFilterDto: {
      /** @default false */
      active: boolean;
      tagsIds: string[];
    };
    UpdateGlobalFilterResponseDto: {
      /** Format: uuid */
      id: string;
      username: string;
      password: string;
      /** @enum {string} */
      role: 'USER' | 'ADMIN';
      /** @default false */
      isGlobalFilterActive: boolean;
      /** @default [] */
      fcmToken: string[];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      globalFilter: {
        /** Format: uuid */
        id: string;
        name: string;
        /** Format: uuid */
        groupId: string;
        /** @enum {string} */
        type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
        /** Format: date-time */
        created_at: string;
        /** Format: date-time */
        updated_at: string;
      }[];
    };
    GetGlobalFilterResponseDto: {
      /** @default false */
      isGlobalFilterActive: boolean;
      globalFilter: {
        /** Format: uuid */
        id: string;
        name: string;
        /** @enum {string} */
        type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
        group: {
          /** Format: uuid */
          id: string;
          color: string;
          isExclusive: boolean;
        };
      }[];
    };
    GetMeResponseDto: {
      /** Format: uuid */
      id: string;
      username: string;
      /** @enum {string} */
      role: 'USER' | 'ADMIN';
      /** @default false */
      isGlobalFilterActive: boolean;
      /** @default [] */
      fcmToken: string[];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      globalFilter: {
        /** Format: uuid */
        id: string;
        name: string;
        /** @enum {string} */
        type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
        group: {
          /** Format: uuid */
          id: string;
          color: string;
          isExclusive: boolean;
        };
      }[];
      tags: {
        /** Format: uuid */
        id: string;
        name: string;
        /** Format: uuid */
        groupId: string;
        /** @enum {string} */
        type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
        /** Format: date-time */
        created_at: string;
        /** Format: date-time */
        updated_at: string;
      }[];
    };
    CreateTagGroupDto: {
      color: string;
      name: string;
      isExclusive: boolean;
    };
    CreateTagGroupResponseDto: {
      /** Format: uuid */
      id: string;
      name: string;
      color: string;
      isExclusive: boolean;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    FindAllTagGroupResponseDto: {
      tagGroups: {
        /** Format: uuid */
        id: string;
        name: string;
        color: string;
        isExclusive: boolean;
        /** Format: date-time */
        created_at: string;
        /** Format: date-time */
        updated_at: string;
        tags: {
          /** Format: uuid */
          id: string;
          name: string;
          /** Format: uuid */
          groupId: string;
          /** @enum {string} */
          type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
          /** Format: date-time */
          created_at: string;
          /** Format: date-time */
          updated_at: string;
        }[];
      }[];
    };
    FindAllWithTagsResponseDto: {
      groups: {
        /** Format: uuid */
        id: string;
        name: string;
        isExclusive: boolean;
        color: string;
        tags: {
          /** Format: uuid */
          id: string;
          name: string;
          /** Format: uuid */
          groupId: string;
          /** @enum {string} */
          type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
          /** Format: date-time */
          created_at: string;
          /** Format: date-time */
          updated_at: string;
          _count: {
            profiles: number;
          };
        }[];
        _count: {
          tags: number;
        };
      }[];
    };
    FindOneTagGroupResponseDto: {
      /** Format: uuid */
      id: string;
      name: string;
      color: string;
      isExclusive: boolean;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      tags: {
        /** Format: uuid */
        id: string;
        name: string;
        /** Format: uuid */
        groupId: string;
        /** @enum {string} */
        type: 'PROFILE' | 'EVENT' | 'PARTICIPANT' | 'NOT_IN_SYSTEM';
        /** Format: date-time */
        created_at: string;
        /** Format: date-time */
        updated_at: string;
      }[];
    };
    UpdateTagGroupDto: {
      name: string;
      color: string;
      isExclusive: boolean;
    };
    UpdateTagGroupResponseDto: {
      /** Format: uuid */
      id: string;
      name: string;
      color: string;
      isExclusive: boolean;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    DeleteTagGroupResponseDto: {
      /** Format: uuid */
      id: string;
      name: string;
      color: string;
      isExclusive: boolean;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    CreateCommentDto: {
      content: string;
      /** Format: uuid */
      profileId: string;
      /** @default false */
      isSolvable: boolean;
    };
    CreateCommentResponseDto: {
      /** Format: uuid */
      id: string;
      content: string;
      /** Format: uuid */
      createdBy: string;
      /** Format: uuid */
      profileId: string;
      /** @default false */
      isSolvable: boolean;
      /** @default false */
      isSolved: boolean;
      /** Format: date-time */
      solvedAt: string | null;
      /** Format: uuid */
      solvedBy: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    GetByProfileCommentResponseDto: {
      comments: {
        /** Format: uuid */
        id: string;
        content: string;
        /** Format: uuid */
        createdBy: string;
        /** Format: uuid */
        profileId: string;
        /** @default false */
        isSolvable: boolean;
        /** @default false */
        isSolved: boolean;
        /** Format: date-time */
        solvedAt: string | null;
        /** Format: uuid */
        solvedBy?: string;
        /** Format: date-time */
        created_at: string;
        /** Format: date-time */
        updated_at: string;
        account: {
          username: string;
        };
      }[];
    };
    ToggleSolveCommentResponseDto: {
      /** Format: uuid */
      id: string;
      content: string;
      /** Format: uuid */
      createdBy: string;
      /** Format: uuid */
      profileId: string;
      /** @default false */
      isSolvable: boolean;
      /** @default false */
      isSolved: boolean;
      /** Format: date-time */
      solvedAt: string | null;
      /** Format: uuid */
      solvedBy: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    FindAllLocationResponseDto: {
      birthLocations: {
        city: string;
        longitude: number;
        latitude: number;
        _count: {
          birthProfiles: number;
        };
      }[];
      residenceLocations: {
        city: string;
        longitude: number;
        latitude: number;
        _count: {
          residenceProfiles: number;
        };
      }[];
    };
    FindProvincesResponseDto: {
      provinces: string[];
    };
    FindCitiesByProvinceLocationResponseDto: {
      cities: {
        id: string;
        name: string;
        centroid: {
          lon: number;
          lat: number;
        };
      }[];
    };
    FindAllCountriesResponseDto: {
      countries: {
        name: string;
        isoCode: string;
      }[];
    };
    FindAllStatesByCountryResponseDto: {
      states: {
        name: string;
        isoCode: string;
        countryCode: string;
        countryName: string;
        latitude?: string | null;
        longitude?: string | null;
      }[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_loginUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      /** @description Cuenta creada */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResponseDto'];
        };
      };
      /** @description Credenciales inválidas */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
    };
  };
  AuthController_refreshToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Token renovado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RefreshResponseDto'];
        };
      };
    };
  };
  TagController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTagDto'];
      };
    };
    responses: {
      /** @description Etiqueta creada con éxito */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreateTagResponseDto'];
        };
      };
    };
  };
  TagController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Etiquetas obtenidas */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FindAllTagResponseDto'];
        };
      };
    };
  };
  TagController_findByGroup: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        groupId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Etiquetas obtenidas */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FindByGroupTagResponseDto'];
        };
      };
      /** @description Grupo de etiquetas no encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
    };
  };
  TagController_findById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Etiqueta obtenida */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FindOneTagResponseDto'];
        };
      };
      /** @description Etiqueta no encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
    };
  };
  TagController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Etiqueta no encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
      /** @description Etiqueta eliminada */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeleteTagResponseDto'];
        };
      };
    };
  };
  TagController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTagDto'];
      };
    };
    responses: {
      /** @description Etiqueta actualizada */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UpdateTagResponseDto'];
        };
      };
      /** @description Etiqueta no encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
    };
  };
  TagController_massiveAllocation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MassiveAllocationDto'];
      };
    };
    responses: {
      /** @description Etiquetas asignadas con éxito */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MassiveAllocationResponseDto'];
        };
      };
    };
  };
  TagController_massiveDeallocation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MassiveDeallocationDto'];
      };
    };
    responses: {
      /** @description Etiquetas desasignadas con éxito */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MassiveDeallocationResponseDto'];
        };
      };
    };
  };
  AccountController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAccountDto'];
      };
    };
    responses: {
      /** @description Cuenta creada con éxito */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreateAccountResponseDto'];
        };
      };
    };
  };
  AccountController_getGlobalFilter: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Filtro base obtenido */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetGlobalFilterResponseDto'];
        };
      };
    };
  };
  AccountController_updateGlobalFilter: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateGlobalFilterDto'];
      };
    };
    responses: {
      /** @description Filtro base actualizado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UpdateGlobalFilterResponseDto'];
        };
      };
    };
  };
  AccountController_getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cuenta obtenida */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetMeResponseDto'];
        };
      };
    };
  };
  TagGroupController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTagGroupDto'];
      };
    };
    responses: {
      /** @description Grupo de etiquetas creado con éxito */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreateTagGroupResponseDto'];
        };
      };
    };
  };
  TagGroupController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Grupos de etiquetas obtenidos */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FindAllTagGroupResponseDto'];
        };
      };
    };
  };
  TagGroupController_findAllWithTags: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Etiquetas obtenidas */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FindAllWithTagsResponseDto'];
        };
      };
    };
  };
  TagGroupController_findById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Grupo de etiquetas obtenido */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FindOneTagGroupResponseDto'];
        };
      };
      /** @description Grupo de etiquetas no encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
    };
  };
  TagGroupController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Grupo de etiquetas eliminado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeleteTagGroupResponseDto'];
        };
      };
      /** @description Grupo de etiquetas no encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
    };
  };
  TagGroupController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTagGroupDto'];
      };
    };
    responses: {
      /** @description Grupo de etiquetas actualizado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UpdateTagGroupResponseDto'];
        };
      };
      /** @description Grupo de etiquetas no encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
    };
  };
  CommentController_createComment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCommentDto'];
      };
    };
    responses: {
      /** @description Comentario creado con éxito */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreateCommentResponseDto'];
        };
      };
      /** @description Perfil no encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
    };
  };
  CommentController_getCommentsByProfileId: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Comentarios obtenidos */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetByProfileCommentResponseDto'];
        };
      };
      /** @description Perfil no encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
    };
  };
  CommentController_toggleSolveComment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cambio de estado en la resolución del comentario */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ToggleSolveCommentResponseDto'];
        };
      };
      /** @description Comentario no encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
      /** @description El comentario no es resoluble */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
    };
  };
  LocationController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ubicaciones obtenidas */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FindAllLocationResponseDto'];
        };
      };
    };
  };
  LocationController_findProvinces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Provincias de Argentina obtenidas */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FindProvincesResponseDto'];
        };
      };
    };
  };
  LocationController_findArgCityByProvince: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        province: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Localidades de Argentina obtenidas */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FindCitiesByProvinceLocationResponseDto'];
        };
      };
    };
  };
  LocationController_findAllCountries: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Países obtenidos */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FindAllCountriesResponseDto'];
        };
      };
    };
  };
  LocationController_findStatesByCountry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        countryCode: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Estados obtenidos */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FindAllStatesByCountryResponseDto'];
        };
      };
      /** @description País no encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorDto'];
        };
      };
    };
  };
}
