import { BLANK_PDF, type Template } from '@pdfme/common';

export const TICKET_INPUTS = {
  footer: 'Este ticket es personal e intransferible.',
  title: 'ENTRADA',
  event_section: 'EVENTO:',
  date_label: 'Fecha:',
  time_label: 'Hora:',
  location_label: 'Lugar:',
  attendee_section: 'ASISTENTE:',
  name_label: 'Nombre:',
  email_label: 'Email:',
  ticket_section: 'DETALLES DEL TICKET:',
  type_label: 'Tipo:',
  status_label: 'Estado:',
};

export const TICKET_TEMPLATE: Template = {
  basePdf: BLANK_PDF,
  schemas: [
    [
      // Campos dinámicos
      {
        name: 'event_name',
        type: 'text',
        position: { x: 30, y: 30 },
        width: 180,
        height: 20,
        fontSize: 14,
        fontWeight: 'bold',
      },
      {
        name: 'event_date',
        type: 'text',
        position: { x: 100, y: 60 },
        width: 180,
        height: 10,
        fontSize: 10,
      },
      {
        name: 'event_time',
        type: 'text',
        position: { x: 100, y: 75 },
        width: 180,
        height: 10,
        fontSize: 10,
      },
      {
        name: 'event_location',
        type: 'text',
        position: { x: 100, y: 90 },
        width: 180,
        height: 10,
        fontSize: 10,
      },
      {
        name: 'fullName_ticket',
        type: 'text',
        position: { x: 100, y: 120 },
        width: 180,
        height: 10,
        fontSize: 10,
      },
      {
        name: 'mail_ticket',
        type: 'text',
        position: { x: 100, y: 135 },
        width: 180,
        height: 10,
        fontSize: 10,
      },
      {
        name: 'ticket_type',
        type: 'text',
        position: { x: 100, y: 165 },
        width: 180,
        height: 10,
        fontSize: 10,
      },
      {
        name: 'ticket_status',
        type: 'text',
        position: { x: 100, y: 180 },
        width: 180,
        height: 10,
        fontSize: 10,
      },
      {
        name: 'ticket_id',
        type: 'text',
        position: { x: 100, y: 195 },
        width: 180,
        height: 10,
        fontSize: 8,
      },

      // Título
      {
        name: 'title',
        type: 'text',
        position: { x: 0, y: 15 },
        content: 'ENTRADA',
        width: 210,
        height: 15,
        fontSize: 16,
        fontWeight: 'bold',
        alignment: 'center',
        value: 'ENTRADA',
      },

      // Secciones y etiquetas
      {
        name: 'event_section',
        type: 'text',
        position: { x: 30, y: 50 },
        content: 'EVENTO:',
        width: 150,
        height: 10,
        fontSize: 12,
        fontWeight: 'bold',
        value: 'EVENTO:',
      },
      {
        name: 'date_label',
        type: 'text',
        position: { x: 30, y: 65 },
        content: 'Fecha:',
        width: 60,
        height: 10,
        fontSize: 10,
        fontWeight: 'bold',
        value: 'Fecha:',
      },
      {
        name: 'time_label',
        type: 'text',
        position: { x: 30, y: 80 },
        content: 'Hora:',
        width: 60,
        height: 10,
        fontSize: 10,
        fontWeight: 'bold',
        value: 'Hora:',
      },
      {
        name: 'location_label',
        type: 'text',
        position: { x: 30, y: 95 },
        content: 'Lugar:',
        width: 60,
        height: 10,
        fontSize: 10,
        fontWeight: 'bold',
        value: 'Lugar:',
      },

      {
        name: 'attendee_section',
        type: 'text',
        position: { x: 30, y: 105 },
        content: 'ASISTENTE:',
        width: 150,
        height: 10,
        fontSize: 12,
        fontWeight: 'bold',
        value: 'ASISTENTE:',
      },
      {
        name: 'name_label',
        type: 'text',
        position: { x: 30, y: 120 },
        content: 'Nombre:',
        width: 60,
        height: 10,
        fontSize: 10,
        fontWeight: 'bold',
        value: 'Nombre:',
      },
      {
        name: 'email_label',
        type: 'text',
        position: { x: 30, y: 135 },
        content: 'Email:',
        width: 60,
        height: 10,
        fontSize: 10,
        fontWeight: 'bold',
        value: 'Email:',
      },

      {
        name: 'ticket_section',
        type: 'text',
        position: { x: 30, y: 150 },
        content: 'DETALLES DEL TICKET:',
        width: 150,
        height: 10,
        fontSize: 12,
        fontWeight: 'bold',
        value: 'DETALLES DEL TICKET:',
      },
      {
        name: 'type_label',
        type: 'text',
        position: { x: 30, y: 165 },
        content: 'Tipo:',
        width: 60,
        height: 10,
        fontSize: 10,
        fontWeight: 'bold',
        value: 'Tipo:',
      },
      {
        name: 'status_label',
        type: 'text',
        position: { x: 30, y: 180 },
        content: 'Estado:',
        width: 60,
        height: 10,
        fontSize: 10,
        fontWeight: 'bold',
        value: 'Estado:',
      },
      // Pie de página
      {
        name: 'footer',
        type: 'text',
        position: { x: 0, y: 220 },
        content: 'Este ticket es personal e intransferible.',
        width: 210,
        height: 10,
        fontSize: 8,
        alignment: 'center',
        value: 'Este ticket es personal e intransferible.',
      },
      // Líneas separadoras
      {
        name: 'separator1',
        type: 'line',
        position: { x: 30, y: 60 },
        width: 150,
        height: 0,
        borderColor: '#000000',
        borderWidth: 1,
      },
      {
        name: 'separator2',
        type: 'line',
        position: { x: 30, y: 115 },
        width: 150,
        height: 0,
        borderColor: '#000000',
        borderWidth: 1,
      },
      {
        name: 'separator3',
        type: 'line',
        position: { x: 30, y: 160 },
        width: 150,
        height: 0,
        borderColor: '#000000',
        borderWidth: 1,
      },
      {
        name: 'ticket_barcode',
        type: 'code128',
        position: { x: 30, y: 240 },
        width: 150,
        height: 30,
        options: {
          displayValue: false,
        },
        readOnly: false,
        includetext: false,
      },
    ],
  ],
  pdfmeVersion: '4.0.0',
};
